ToolGether/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Web_Main.urls")),
    path('account/', include("Web_Login.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

Web_Login/urls.py
from django.urls import path, include
from Web_Login import views

app_name = 'Web_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('editprofile', views.edit_profile, name='edit_profile'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/<int:pk>/', views.profile_view, name='profile'),
    path('item/list/', views.listTool, name='listTool'),
    path('item/<int:pk>/', views.item_view, name='itempage'),
    path('messages/', views.user_messages, name='messages')
    # path('', views.profile_view.as_view(), name='user'),
]

Web_Main/urls.py
from django.urls import path
from Web_Main import views

app_name = 'Web_Main'

urlpatterns = [
    path('', views.Home, name='index'),
    path('about/', views.About, name='about'),
    path('credits/', views.Credits, name='credits'),
    path('item/', views.Item, name='item'),
    path('search/', views.Search, name='search'),
]

Web_Login/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy
import random
import os

# Create your models here.

# To automatically create one to one objects
from django.db.models.signals import post_save
from django.dispatch import receiver

class MyUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The email must be provided")
        if not password:
            raise ValueError("The password must be provided")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email=models.EmailField(unique=True, null=False)

    is_staff=models.BooleanField(
        gettext_lazy('Staff Status'), default=False,
        help_text=gettext_lazy('Designates whether the user can login the site')
        )
    
    is_active=models.BooleanField(
        gettext_lazy('active'), default=True,
        help_text=gettext_lazy('Designates whether this user should be treated as active')
        )
    
    USERNAME_FIELD = 'email'
    objects=MyUserManager()

    def __str__(self):
        return self.email
    
    def get_full_name(self):
        return self.email
    
    def get_short_name(self):
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    firstname = models.CharField(max_length=264, blank=True, default="John")
    lastname = models.CharField(max_length=264, blank=True, default="Smith")
    address = models.TextField(max_length=300, blank=True, default="000")
    postcode = models.CharField(max_length=10, blank=True, default="000")
    phone = models.CharField(max_length=20, blank=True, default="000")
    date_joined = models.DateTimeField(auto_now_add=True)

    def imageFolder():
        same = True
        while same == True:
            imageFolder = random.randint(100000000, 999999999)
            if os.path.exists("media/profile_img/" + str(imageFolder)):
                same = True
            else:
                same = False
        return str(imageFolder)
    
    a = imageFolder()
    profile_picture = models.ImageField(upload_to='media/profile_img/{}'.format(a), blank=True, default="media\pg.png")

    def __str__(self):
        return self.firstname + "'s Profile"
    
    def is_fully_filled(self):
        fields_name = [f.name for f in self._meta.get_fields()]
        for fields_name in fields_name:
            value = getattr(self, fields_name)
            if value is None or value == '':
                return False
        return True


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

Web_Login/forms.py
from django.forms import ModelForm
from Web_Login.models import User, Profile
from Web_Main.models import Item

from django.contrib.auth.forms import UserCreationForm

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('firstname','lastname','address', 'postcode', 'phone')

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

class ToolListForm(ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'category', 'description', 'price', 'image_1', 'image_2', 'image_3', 'image_4', 'image_5')

Web_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import TemplateView, DetailView

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate

from Web_Login.models import Profile
from Web_Main.models import Item
from Web_Login.forms import ProfileForm, SignUpForm, ToolListForm

# Message
from django.contrib import messages

# Create your views here.

def sign_up(request):
    form=SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully!')
            return HttpResponseRedirect(reverse('Web_Login:login'))
    return render(request, 'Web_Login/signup.html', context={'form':form})

def login_user(request):
    form= AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('Web_Main:index'))
    return render(request, 'Web_Login/login.html', context={'form':form})

# class profile_view(DetailView):
#     model = Profile
#     userTools = Item.objects.all().filter(author = model.user)
#     template_name = "Web_Login/profile.html"
    
def profile_view(request, pk):
    profile = Profile.objects.get(id = pk)
    userTools = Item.objects.all().filter(author = profile.user)
    context={'profile':profile, 'userTools':userTools}
    return render(request, "Web_Login/profile.html", context)

@login_required
def logout_user(request):
    logout(request)
    messages.warning(request, 'You have been logged out!')
    return HttpResponseRedirect(reverse('Web_Main:index'))

@login_required
def user_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully!')
            form = ProfileForm(instance=profile)
    return render(request, 'Web_Login/profile.html', context={'form':form})

@login_required
def listTool(request):
    form = ToolListForm(request.POST, request.FILES)
    if request.method == 'POST':
        form = ToolListForm(request.POST, request.FILES)
        if form.is_valid():
            setTool = form.save(commit=False)
            setTool.author = request.user
            setTool.save
            messages.success(request, 'Tool listed successfully!')
            return HttpResponseRedirect(reverse('Web_Main:index'))
    return render(request, 'Web_Main/listTool.html', context={'form':form})

def item_view(request, pk):
    model = Item.objects.get(id = pk)
    allTools = Item.objects.all()
    userEmail = model.author
    userData = Profile.objects.get(user = userEmail)
    categoryTools = Item.objects.all().filter(category = model.category)[:3]

    images = [model.image_2, model.image_3, model.image_4, model.image_5]

    context={'model':model, 'allTools':allTools, 'userData':userData, 'images':images, 'categoryTools':categoryTools}
    return render(request, "Web_Main/item.html", context)

@login_required
def user_messages(request):
    return render(request, 'Web_Profile/messages.html')

@login_required
def edit_profile(request):
    form = ProfileForm()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile Updated')
            return HttpResponseRedirect(reverse('Web_Main:index'))
    return render(request, 'Web_Profile/edit_profile.html', context={'form':form})

templates/Web_Login/login.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
{% load static %} Login {% endblock %} {% block main %}

<style>
  .calltoaction {
    background-color: #23283d;
    color: #fff;
    border: 2px solid #e56a4c;
    box-shadow: 2px 2px 5px #23283d;
    padding: 0.5rem 1rem;
  }

  .calltoaction:hover {
    background-color: #e56a4c;
    color: #23283d;
    border-color: #e56a4c;
  }
</style>

<div class="container text-center">
  <div class="row">
    <div class="col">
      <img
        style="border-radius: 5%; object-fit: cover; height: 600px; width: 100%"
        class="rounded"
        src="{% static 'img/abc.png' %}"
        alt=""
      />
    </div>
    <div class="col">
      <div class="container text-white text-start rounded">
        <h1 class="mt-3">Login</h1>
        <form method="POST" class="mt-3 w-75">
          {{ form|crispy }} {% csrf_token %}
          <button type="submit" class="btn btn-light mt-2 p-2 px-5">
            Login
          </button>
        </form>
        <br />
        <p>
          Need an account?
          <a href="{% url 'Web_Login:signup' %}">Create Account</a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/Web_Login/profile.html
{% extends "base.html" %} {% block main %} {% load static %}
<div class="container text-center">
  <div class="row">
    <div class="col-12">
      <img
        style="
          border-radius: 50%;
          object-fit: cover;
          width: 200px;
          height: 200px;
        "
        class="img-thumbnail"
        src="{% static 'img/pg.png' %}"
        alt=""
      />
    </div>
    <div class="col-12 mt-2">
      <h1 class="text-white">
        {{ profile.firstname }} <span class="badge bg-secondary">New</span>
      </h1>
    </div>
    {% if user == profile.user %}
    <div>
      <a
        href="{% url 'Web_Login:edit_profile'%}"
        type="button"
        class="btn calltoaction"
        style="
          --bs-btn-padding-y: 0.5rem;
          --bs-btn-padding-x: 4rem;
          --bs-btn-font-size: 1rem;
        "
        >Edit Profile</a
      >
    </div>
    {% endif %}
    <div class="col-6 mt-2">
      <a
        type="button"
        class="btn calltoaction"
        style="
          --bs-btn-padding-y: 0.5rem;
          --bs-btn-padding-x: 4rem;
          --bs-btn-font-size: 1rem;
        "
        >Contact</a
      >
    </div>
    <div class="col-6 mt-2">
      <a
        type="button"
        class="btn calltoaction"
        style="
          --bs-btn-padding-y: 0.5rem;
          --bs-btn-padding-x: 4rem;
          --bs-btn-font-size: 1rem;
        "
        >Report User</a
      >
    </div>
  </div>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col-2">
      <h1></h1>
    </div>
    <div class="col-8">
      <h1 class="border-top text-center text-white mt-4 p-2">
        User's Listed Tools
      </h1>
    </div>
    <div class="col-2">
      <h1></h1>
    </div>
  </div>
</div>

<div class="container text-white p-5">
  <h5 class="fw-bold"></h5>
  <div class="row">
    {% for i in userTools %}
    <div class="col-3 p-4 zoom">
      <a href="{% url 'Web_Login:itempage' i.pk %}">
        <img
          src="{{ i.image_1.url }}"
          class="rounded"
          style="width: 200px; height: 200px; object-fit: cover"
      /></a>
      <p class="fw-bold mt-2 mb-2">{{ i.name }}</p>
      <p class="mb-2"><b>Deposit</b> £{{ i.price }}</p>
      <div class="d-inline-flex align-items-center">
        <ion-icon name="location-outline" class="me-2"></ion-icon>
        <p class="ms-1 mb-0">{{ i.district }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<div class="container text-center">
  <div class="row">
    <div class="col-1">
      <h1></h1>
    </div>
    <div class="col-10">
      <h1 class="border-top text-center text-white mt-5 p-2">User Badges</h1>
    </div>
    <div class="col-1">
      <h1></h1>
    </div>
  </div>
</div>
{% endblock main %}

templates/Web_Login/signup.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
Sign Up {% endblock %} {% block main %} {% load static %}

<style>
  .calltoaction {
    background-color: #23283d;
    color: #fff;
    border: 2px solid #e56a4c;
    box-shadow: 2px 2px 5px #23283d;
    padding: 0.5rem 1rem;
  }

  .calltoaction:hover {
    background-color: #e56a4c;
    color: #23283d;
    border-color: #e56a4c;
  }
</style>
<div class="container text-center">
  <div class="row">
    <div class="col">
      <img
        style="border-radius: 5%; object-fit: cover; height: 600px; width: 100%"
        class="rounded"
        src="{% static 'img/abc.png' %}"
        alt=""
      />
    </div>
    <div class="col" style="">
      <div class="container text-white text-start">
        <h1 class="mt-3">Sign Up</h1>
        <form method="POST" class="mt-2 w-75">
          {{ form|crispy }} {% csrf_token %}
          <button type="submit" class="btn btn-light mt-2 p-2 px-5">
            Create Account
          </button>
        </form>
        <br />
        <p>
          Already have an account?
          <a href="{% url 'Web_Login:login' %}">Login Here</a>
        </p>
      </div>
    </div>
  </div>

  <style>
    li {
      color: #fff;
    }

    .form-text {
      color: #fff;
    }
  </style>
  {% endblock %}
</div>