ToolGether/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Web_Main.urls")),
    path('account/', include("Web_Login.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

Web_Login/urls.py
from django.urls import path, include
from Web_Login import views

app_name = 'Web_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('editprofile', views.edit_profile, name='edit_profile'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/<int:pk>/', views.profile_view, name='profile'),
    path('item/list/', views.listTool, name='listTool'),
    path('item/<int:pk>/', views.item_view, name='itempage'),
    path('messages/', views.user_messages, name='messages')
    # path('', views.profile_view.as_view(), name='user'),
]

Web_Main/urls.py
from django.urls import path
from Web_Main import views

app_name = 'Web_Main'

urlpatterns = [
    path('', views.Home, name='index'),
    path('about/', views.About, name='about'),
    path('credits/', views.Credits, name='credits'),
    path('item/', views.Item, name='item'),
    path('search/', views.Search, name='search'),
]

Web_Main/models.py
from django.db import models
from Web_Login.models import User
import random
import os


# Create your models here.

class category(models.Model):
    title = models.CharField(max_length=30)
    image = models.ImageField(upload_to='category/', blank=False, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Categories'

class slider(models.Model):
    title = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to='slider/', blank=False)
    
    def __str__(self):
        return self.title

class Item(models.Model):
    
    name = models.CharField(max_length=264)
    category = models.ForeignKey(category, related_name='category', on_delete=models.CASCADE)
    description = models.TextField(max_length=200, verbose_name='Description')
    rented = models.BooleanField(default=False)
    price = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    districtChoices = (('Atlantic Wharf','Atlantic Wharf'),
('Birchgrove', 'Birchgrove'),
('Butetown', 'Butetown'),
('Cardiff Bay','Cardiff Bay'),
('Cardiff city centre','Cardiff city centre'),
('Cardiff Gate','Cardiff Gate'),
('Castle Quarter', 'Castle Quarter'),
('Cathays Park', 'Cathays Park'),
('Cefn Mably', 'Cefn Mably'),
('Coryton, Cardiff', 'Coryton, Cardiff'),
('Culverhouse Cross', 'Culverhouse Cross'),
('Cyncoed', 'Cyncoed'),
('Danescourt', 'Danescourt'),
('Ely, Cardiff', 'Ely, Cardiff'),
('Gabalfa', 'Gabalfa'),
('The Hayes', 'The Hayes'),
('Cardiff International Sports Village', 'Cardiff International Sports Village'),
('Leckwith, Cardiff', 'Leckwith, Cardiff'),
('Llandaff', 'Llandaff'),
('Maindy', 'Maindy'),
('Mermaid Quay', 'Mermaid Quay'),
('Morganstown', 'Morganstown'),
('Mynachdy', 'Mynachdy'),
('Pentrebane', 'Pentrebane'),
('Plasdwr', 'Plasdwr'),
('Pwll-coch', 'Pwll-coch'),
('Radyr', 'Radyr'),
('Rhiwbina', 'Rhiwbina'),
('Rhydlafar', 'Rhydlafar'),
('Roath', 'Roath'),
('St Mellons', 'St Mellons'),
('Tiger Bay', 'Tiger Bay'),
('Tremorfa', 'Tremorfa'))
    
    district = models.CharField(max_length=50, choices=districtChoices, default='Cardiff city centre')

    def imageFolder():
        same = True
        while same == True:
            imageFolder = random.randint(100000000, 999999999)
            if os.path.exists("media/item_img/" + str(imageFolder)):
                same = True
            else:
                same = False
        return str(imageFolder)
    
    a = imageFolder()
        
    image_1 = models.ImageField(upload_to='media/item_img/{}'.format(a), null=True, blank=True)
    image_2 = models.ImageField(upload_to='media/item_img/{}'.format(a), null=True, blank=True)
    image_3 = models.ImageField(upload_to='media/item_img/{}'.format(a), null=True, blank=True)
    image_4 = models.ImageField(upload_to='media/item_img/{}'.format(a), null=True, blank=True)
    image_5 = models.ImageField(upload_to='media/item_img/{}'.format(a), null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created'] # descending order

Web_Main/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from Web_Main.models import category, slider, Item

# Create your views here.

def Home(request):
    categorydata = category.objects.all()
    sliderdata = slider.objects.all()
    itemdata = Item.objects.all()
    if itemdata.count() > 6:
        itemdata = itemdata[:]
    context = {
        'category': categorydata,
        'slider': sliderdata,
        'items': itemdata,
    }
    return render(request, 'Web_Main/index.html', context)

def About(request):
    return render(request, 'Web_Main/about.html')

def Credits(request):
    return render(request, 'Web_Main/credits.html')

def ItemPage(request):
    return render(request, 'Web_Main/item.html')

def Search(request):
    itemdata = Item.objects.all()
    context = {

        'c': itemdata,
    }
    return render(request, 'Web_Main/search.html', context)

templates/Web_Main/about.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
{% load static %} About Us {% endblock %} {% block main %}

<style>
  .calltoaction {
    background-color: #23283d;
    color: #fff;
    border: 2px solid #e56a4c;
    box-shadow: 2px 2px 5px #23283d;
    padding: 0.5rem 1rem;
  }

  .calltoaction:hover {
    background-color: #e56a4c;
    color: #23283d;
    border-color: #e56a4c;
  }
</style>

<div class="container text-center">
  <div class="row">
    <h1 class="text-white">
      What is
      <img
        id="ToolgetherLogo"
        src="{% static 'img/toolgether-logo.png' %}"
        style="width: 15%"
      />?
    </h1>
  </div>
</div>

<div class="container text-center mt-5">
  <div class="row">
    <div class="col">
      <div class="container text-white text-start">
        <h1>The Mission</h1>
        <p1>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. At ipsa
          quisquam dolorum blanditiis asperiores sed error hic maxime. Quos
          perferendis ad quam facere laboriosam vel, quia ex saepe fugit itaque.
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. At ipsa
          quisquam dolorum blanditiis asperiores sed error hic maxime. Quos
          perferendis ad quam facere laboriosam vel, quia ex saepe fugit itaque.
        </p1>

        <h1 class="mt-3">What can you do?</h1>
        <p1>
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. At ipsa
          quisquam dolorum blanditiis asperiores sed error hic maxime. Quos
          perferendis ad quam facere laboriosam vel, quia ex saepe fugit itaque.
          Lorem, ipsum dolor sit amet consectetur adipisicing elit. At ipsa
          quisquam dolorum blanditiis asperiores sed error hic maxime. Quos
          perferendis ad quam facere laboriosam vel, quia ex saepe fugit itaque.
        </p1>
      </div>
    </div>
    <div class="col">
      <img
        style="
          border-radius: 5%;
          object-fit: cover;
          height: 400px;
          width: 100%;
          transform: rotate(180deg);
        "
        class=""
        src="{% static 'img/abc.png' %}"
        alt=""
      />
    </div>
  </div>
</div>

{% endblock %}

templates/Web_Main/credits.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
{% load static %} About Us {% endblock %} {% block main %}
<div class="container text-center">
  <div class="row">
    <h1 class="text-white">Web Application Development Team</h1>
  </div>
</div>

<div class="container text-center mt-5">
  <div class="row">
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Yang</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Loic</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Adam</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Sally</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Avery</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Jake</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Chris</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card" style="width: 18rem">
        <img
          class="card-img-top"
          src="{% static 'img/pg.png' %}"
          alt="Card image cap"
        />
        <div class="card-body">
          <h5 class="card-title">Harry</h5>
          <p class="card-text">
            Some quick example text to build on the card title and make up the
            bulk of the card's content.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/Web_Main/index.html
{% extends "base.html" %} {% block main %} {% load static %} {% if user.is_authenticated == False %}{% include 'landingpage.html'%}{% endif %}

{% if user.is_authenticated %}
<h1 class="text-white text-center mb-3">Hello,{{ user.firstname }} 👋</h1>
{% endif %}

<div
  class="container mt-1 p-3 pt-5 w-50 rounded"
  style="background: rgba(255, 255, 255, 0.123);"
>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h1 class="text-center text-white mb-2" style="font-size: 30px;">Search for a tool!</h1>
      <form
        class=""
        role="search"
        method="post"
        action="{% url 'Web_Main:search' %}"
      >
        {% csrf_token %}
        <input
          type="search"
          class="form-control form-control-white text-white"
          placeholder="Search..."
          aria-label="Search"
        />
      </form>
    </div>
    <div class="col-3"></div>
  </div>
</div>

<div class="container text-white mt-5">
  <h5 class="mb-3">Browse by categories</h5>
  <div class="row text-center">
    {% for c in category %}
    <div class="col">
      <img class="img-fluid" src="{{ c.image.url }}" />
      <p>{{ c.title }}</p>
    </div>
    {% endfor %}
  </div>
</div>

<div class="container text-white mt-4">
  <h5 class="mb-3">Latest Tools</h5>
  <div class="row">
    {% for i in items %}
    <div class="col-3 p-4 zoom">
      <a href="{% url 'Web_Login:itempage' i.pk %}">
        <img
          src="{{ i.image_1.url }}"
          class="rounded"
          style="width: 200px; height: 200px; object-fit: cover"
      /></a>
      <p class="fw-bold mt-2 mb-2">{{ i.name }}</p>
      <p class="mb-2"><b>Deposit</b> £20.00</p>
      <div class="d-inline-flex align-items-center">
        <ion-icon name="location-outline" class="me-2"></ion-icon>
        <p class="ms-1 mb-0">{{ i.district }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<hr
  style="
    background-color: white;
    border-radius: 5px;
    height: 5px;
    width: 75%;
    margin: auto;
    margin-top: 2em;
  "
/>

{% include 'slider.html' with sliderdata=slider %} {% endblock main %}

templates/Web_Main/item.html
{% extends "base.html" %} {% block main %} {% load static %}

<style>
  .calltoaction {
    background-color: #23283d;
    color: #fff;
    border: 2px solid #e56a4c;
    box-shadow: 2px 2px 5px #23283d;
    padding: 0.5rem 1rem;
  }

  .calltoaction:hover {
    background-color: #e56a4c;
    color: #23283d;
    border-color: #e56a4c;
  }
</style>
<script>
  let items = document.querySelectorAll(".carousel .carousel-item");

  items.forEach((el) => {
    const minPerSlide = 2;
    let next = el.nextElementSibling;
    for (var i = 1; i < minPerSlide; i++) {
      if (!next) {
        // wrap carousel by using first child
        next = items[0];
      }
      let cloneChild = next.cloneNode(true);
      el.appendChild(cloneChild.children[0]);
      next = next.nextElementSibling;
    }
  });
</script>

<!-- Slider -->

<div class="container text-center my-3 border border-white p-5 rounded w-50">
  <div class="row mx-auto my-auto justify-content-center text-center">
    <div id="recipeCarousel" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
          <div class="col-md-3">
            <div class="card-img">
              <img
                src="{{ model.image_1.url }}"
                class="img-fluid border rounded"
                style="width: 500px; height: 200px; object-fit: cover"
              />
            </div>
          </div>
        </div>
        {% for img in images %}
        <div class="carousel-item">
          <div class="col-md-3">
            <div class="card-img">
              <img
                src="{{ img.url }}"
                class="img-fluid text-center border rounded"
                style="width: 500px; height: 200px; object-fit: cover"
              />
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <a
        class="carousel-control-prev bg-transparent w-aut"
        href="#recipeCarousel"
        role="button"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      </a>
      <a
        class="carousel-control-next bg-transparent w-aut"
        href="#recipeCarousel"
        role="button"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
      </a>
    </div>
  </div>
</div>

<!-- Item info -->
<div class="container mt-1 text-white border-bottom p-5">
  <div class="row">
    <div class="col">
      <div class="d-inline-flex align-items-center">
        <ion-icon name="folder-open-outline" class="me-2"></ion-icon>
        <p class="p-0 m-0">Category: {{ model.category }}</p>
      </div>

      <h1 class="fw-bold mt-4 mb-4">{{ model.name }}</h1>

      <div class="d-inline-flex align-items-center">
        <ion-icon name="cash-outline" class="me-2"></ion-icon>
        <p class="fw-bold p-0 m-0">Price</p>
      </div>
      <p>£{{ model.price }}</p>

      <div class="d-inline-flex align-items-center">
        <ion-icon name="calendar-outline" class="me-2"></ion-icon>
        <p class="fw-bold p-0 m-0">Availability</p>
      </div>
      <p>From 12-10-2022 To 15-10-2022</p>

      <div class="d-inline-flex align-items-center">
        <ion-icon name="location-outline" class="me-2"></ion-icon>
        <p class="fw-bold p-0 m-0">Location</p>
      </div>
      <p>{{ model.district }}</p>

      <div class="d-inline-flex align-items-center">
        <ion-icon name="document-text-outline" class="me-2"></ion-icon>
        <p class="fw-bold p-0 m-0">Description</p>
      </div>
      <p>{{ model.description }}</p>
    </div>

    <div class="col">
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button
          class="btn btn-coral-orange me-md-2 rounded-pill text-white"
          type="button"
        >
          Borrow Now
        </button>
        <button
          class="btn btn-outline-coral-orange rounded-pill text-coral-orange"
          type="button"
        >
          Save it for later
        </button>
      </div>
    </div>
  </div>
</div>

<div class="container text-white border-bottom p-5">
  <h5 class="fw-bold mb-4">Tool Owner</h5>
  <div class="row">
    <div class="col-md-4">
      <img
        style="
          border-radius: 50%;
          object-fit: cover;
          width: 150px;
          height: 150px;
        "
        class="img-thumbnail"
        src="{{ userData.profile_picture.url }}"
        alt=""
      />
    </div>
    <div class="col-md-8">
      <p class="fw-bold">{{ userData.firstname }}</p>
      <p class="fw-bold mb-0">Joined since</p>
      <p>{{ userData.date_joined }}</p>
      <p class="fw-bold mb-0">Rating</p>
      <div class="d-inline-flex align-items-center">
        <p class="p-0 mt-0 mb-0 me-2">3.6</p>
        <ion-icon name="star"></ion-icon>
        <ion-icon name="star"></ion-icon>
        <ion-icon name="star"></ion-icon>
        <ion-icon name="star-half"></ion-icon>
        <ion-icon name="star-outline"></ion-icon>
      </div>
    </div>
  </div>
</div>

<div class="container text-white p-5">
  <h5 class="fw-bold">Similar listings</h5>
  <div class="row">
    {% for c in categoryTools %}
    <div class="col-3 p-4 zoom">
      <a href="{% url 'Web_Login:itempage' c.pk %}">
        <img
          src="{{ c.image_1.url }}"
          class="rounded"
          style="width: 200px; height: 200px; object-fit: cover"
      /></a>
      <p class="fw-bold mt-2 mb-2">{{ c.name }}</p>
      <p class="mb-2"><b>Price: </b>£{{ c.price }}</p>
      <div class="d-inline-flex align-items-center">
        <ion-icon name="location-outline" class="me-2"></ion-icon>
        <p class="ms-1 mb-0">{{ c.district }}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock main %}

templates/Web_Main/listTool.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title_block %}
{% load static %} About Us {% endblock %} {% block main %}

<style>
  .calltoaction {
    background-color: #23283d;
    color: #fff;
    border: 2px solid #e56a4c;
    box-shadow: 2px 2px 5px #23283d;
    padding: 0.5rem 1rem;
  }

  .calltoaction:hover {
    background-color: #e56a4c;
    color: #23283d;
    border-color: #e56a4c;
  }
</style>

<div style="position: relative">
  <div class="" style="position: relative; top: 0; left: 0">
    <!-- <img
      style="border-radius: 5%"
      class="rounded"
      src="{% static 'img/abc.png' %}"
      alt=""
    /> -->
  </div>
  <div
    class="container text-white text-start rounded"
    style="position: relative; top: 0; left: 0"
  >
    <h1 class="mt-3">List Your Tool</h1>
    <form method="POST" class="mt-3 w-75">
      {{ form|crispy }} {% csrf_token %}
      <button type="submit" class="btn btn-light mt-2 p-2 px-5">
        List Tool
      </button>
    </form>
    <br />
  </div>
</div>

{% endblock %}

templates/Web_Main/search.html
{% extends "base.html" %} {% block main %} {% load static %}

<style>
  .calltoaction {
    background-color: #23283d;
    color: #fff;
    border: 2px solid #e56a4c;
    box-shadow: 2px 2px 5px #23283d;
    padding: 0.5rem 1rem;
  }

  .calltoaction:hover {
    background-color: #e56a4c;
    color: #23283d;
    border-color: #e56a4c;
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-sm"></div>
    <div class="col-sm">
      <h1 class="text-center text-white">Find your tool!</h1>
      <form
        class="nav"
        role="search"
        method="post"
        action="{% url 'Web_Main:search' %}"
      >
        {% csrf_token %}
        <input
          type="search"
          class="form-control form-control-white text-white"
          placeholder="Search..."
          aria-label="Search"
        />
      </form>
    </div>
    <div class="col-sm"></div>
  </div>
</div>

<div class="container mt-4">
  <div class="row">
    {% for i in c %}
    <div class="col-3 mt-4">
      <a href="{% url 'Web_Main:item' %}"
        ><img class="img-fluid" src="https://unsplash.it/600/600"
      /></a>
    </div>
    <div class="col-3 mt-4 border border-white">
      <h1 class="text-white">TOOL NAME</h1>
      <p class="text-white">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum nostrum
        molestias, at fugiat facilis dicta ut quasi obcaecati nihil, dolore
        totam delectus. Iusto accusamus obcaecati cum sequi. Maxime, expedita
        animi!
      </p>
      <h4 class="text-white">Category: Tool</h4>
      <h5 class="text-white">Price: £20.00 (Deposit: £5.00)</h5>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock main %}